# -*- coding: utf-8 -*-
"""data_wrangling_alfagift.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwVndhOfkX--a3V6Lkn7m0lONA9ZINGI
"""

import pandas as pd
import numpy as np

# 1. Load data
df = pd.read_csv('alfagift_scrape.csv')

# 2. Cek 5 baris pertama (Biar tau bentuk datanya kayak gimana)
print("--- PREVIEW DATA ---")
display(df.head())

# 3. Cek tipe data dan jumlah baris (Biar tau ada data yang kosong atau formatnya aneh)
print("\n--- INFO DATA ---")
df.info()

# 4. Cek total missing values per kolom
print("\n--- MISSING VALUES ---")
print(df.isnull().sum())

# 1. Buang kolom Unnamed 0
df = df.drop(columns=['Unnamed: 0'])

# 2. Operasi Pembersihan Kolom Harga
print("Membersihkan teks harga menjadi angka...")
df['price'] = df['price'].astype(str).str.replace('.', '', regex=False)
df['price'] = pd.to_numeric(df['price'], errors='coerce')

# 3. Buang 1.426 baris yang harganya kosong (NaN)
print(f"Jumlah baris sebelum dibersihkan: {len(df)}")
df_clean = df.dropna(subset=['price']).copy()
print(f"Jumlah baris setelah dibersihkan: {len(df_clean)}")

# 4. Standarisasi nama produk untuk persiapan AI nanti
df_clean['product_clean'] = df_clean['product'].str.lower().str.strip()

print("\n--- PREVIEW DATA BERSIH ---")
display(df_clean[['product_clean', 'price', 'Subcategory']].head())

# Mengambil daftar subkategori unik
unique_subcats = df_clean['Subcategory'].unique()

print(f"Total ada {len(unique_subcats)} subkategori unik di data kita.\n")
print("Ini daftarnya:")
for i, sub in enumerate(unique_subcats, start=1):
    print(f"{i}. {sub}")

# 1. Dictionary Mapping Hasil Diskusi Tim
master_mapping = {
    # --- NEEDS: Makan & Minum Harian ---
    'Bahan Masakan': 'Makan & Minum Harian',
    'Bahan Roti & Kue': 'Makan & Minum Harian',
    'Bahan Puding & Agar-Agar': 'Makan & Minum Harian',
    'Makanan Instan': 'Makan & Minum Harian',
    'Roti, Selai, & Sereal': 'Makan & Minum Harian',
    'Produk Olahan Susu': 'Makan & Minum Harian',
    'Minuman Instan': 'Makan & Minum Harian',
    'Makanan Siap Saji': 'Makan & Minum Harian',
    'Minuman Siap Saji': 'Makan & Minum Harian',
    'Makanan Segar': 'Makan & Minum Harian',
    'Makanan Beku': 'Makan & Minum Harian',
    'Makanan Kemasan': 'Makan & Minum Harian',
    'Makanan Bayi & Anak': 'Makan & Minum Harian',
    'Susu Formula Bayi & Anak': 'Makan & Minum Harian',
    'Susu Ibu Hamil & Menyusui': 'Makan & Minum Harian',

    # --- NEEDS: Kebutuhan Rumah & Mandi ---
    'Perlengkapan Dapur & Ruang Makan': 'Kebutuhan Rumah & Mandi',
    'Perlengkapan Kamar Mandi': 'Kebutuhan Rumah & Mandi',
    'Perawatan & Pembersih': 'Kebutuhan Rumah & Mandi',
    'Perlengkapan Rumah': 'Kebutuhan Rumah & Mandi',
    'Tisu': 'Kebutuhan Rumah & Mandi',
    'Pengharum Ruangan & Anti Lembab': 'Kebutuhan Rumah & Mandi',
    'Pembasmi Hama & Serangga': 'Kebutuhan Rumah & Mandi',
    'Perawatan Tubuh': 'Kebutuhan Rumah & Mandi',
    'Perawatan Pria': 'Kebutuhan Rumah & Mandi',
    'Perawatan Rambut': 'Kebutuhan Rumah & Mandi',
    'Pembalut & Popok Dewasa': 'Kebutuhan Rumah & Mandi',
    'Perawatan Gigi & Mulut': 'Kebutuhan Rumah & Mandi',
    'Obat-Obatan': 'Kebutuhan Rumah & Mandi',
    'Alat Kesehatan': 'Kebutuhan Rumah & Mandi',
    'Produk Higienis': 'Kebutuhan Rumah & Mandi',
    'Perlengkapan Mandi & Perawatan Anak': 'Kebutuhan Rumah & Mandi',
    'Pembersih Pakaian & Perlengkapan Anak': 'Kebutuhan Rumah & Mandi',
    'Perlengkapan Makan & Minum Anak': 'Kebutuhan Rumah & Mandi',
    'Kebutuhan Ibu, Bayi, & Anak Lainnya': 'Kebutuhan Rumah & Mandi',
    'Popok Bayi & Anak': 'Kebutuhan Rumah & Mandi',

    # --- WANTS: Jajan & Nongkrong ---
    'Makanan Ringan': 'Jajan & Nongkrong',
    'Minuman Ringan': 'Jajan & Nongkrong',
    'Es Krim': 'Jajan & Nongkrong',

    # --- WANTS: Hobi & Self-Reward ---
    'Peralatan Rias & Tata Rambut': 'Hobi & Self-Reward',
    'Perawatan Wajah': 'Hobi & Self-Reward',
    'Riasan Wajah & Tubuh': 'Hobi & Self-Reward',
    'Parfum & Cologne': 'Hobi & Self-Reward',
    'Mainan & Hiburan': 'Hobi & Self-Reward',
    'Fashion': 'Hobi & Self-Reward',
    'Makanan Anjing': 'Hobi & Self-Reward',
    'Makanan Kucing': 'Hobi & Self-Reward',
    'Makanan Hewan Peliharan Lainnya': 'Hobi & Self-Reward',

    # --- OTHERS: Lain-lain & Darurat ---
    'Vitamin & Suplemen': 'Lain-lain & Darurat',
    'Perlengkapan Kantor & Sekolah': 'Lain-lain & Darurat',
    'Perlengkapan Otomotif': 'Lain-lain & Darurat'
}

# 2. Eksekusi Mapping ke Kolom Baru
df_clean['Master_Category'] = df_clean['Subcategory'].map(master_mapping)

# 3. Validasi: Apakah ada yang terlewat?
lupa_dimap = df_clean[df_clean['Master_Category'].isnull()]['Subcategory'].unique()

if len(lupa_dimap) > 0:
    print("❌ WARNING! Ada kategori yang belum masuk ke kamus mapping:")
    print(lupa_dimap)
else:
    print("✅ AMAN! Semua 50 Subkategori sudah berhasil dipetakan ke Master Category.")

    # 4. Tambahkan Macro Category (Top Level)
    macro_mapping = {
        'Makan & Minum Harian': 'NEEDS',
        'Kebutuhan Rumah & Mandi': 'NEEDS',
        'Jajan & Nongkrong': 'WANTS',
        'Hobi & Self-Reward': 'WANTS',
        'Lain-lain & Darurat': 'OTHERS'
    }
    df_clean['Macro_Category'] = df_clean['Master_Category'].map(macro_mapping)

    # 5. Rapikan urutan kolom dan Simpan ke CSV baru
    kolom_final = ['product_clean', 'price', 'Macro_Category', 'Master_Category', 'Subcategory', 'Category']
    df_final = df_clean[kolom_final]

    # Simpan hasil akhirnya
    nama_file_baru = 'alfagift_final_dataset.csv'
    df_final.to_csv(nama_file_baru, index=False)

    print(f"\n📁 Selesai! Data final (sebanyak {len(df_final)} baris) telah disimpan sebagai '{nama_file_baru}'")

    # Tampilkan 5 sampel data acak untuk melihat hasilnya
    print("\n--- PREVIEW HASIL AKHIR ---")
    display(df_final.sample(5))